### ISSUE TITLE
Cannot find module node-pty

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.xterm#1]
Hallo,

Fehler in Version 0.2.0  , Adapter Rot.

`
<html>
<body>

host.MedionHome) | 2021-09-19 11:04:20.486 | error | host.Medion(Home) instance system.adapter.xterm.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.MedionHome) | 2021-09-19 11:04:20.486 | error | host.Medion(Home) Caught by controller[0]: }
host.MedionHome) | 2021-09-19 11:04:20.485 | error | host.Medion(Home) Caught by controller[0]: ]
host.MedionHome) | 2021-09-19 11:04:20.485 | error | host.Medion(Home) Caught by controller[0]: 'C:\\Program Files\\iobroker\\Home\\node_modules\\iobroker.xterm\\main.js'
host.MedionHome) | 2021-09-19 11:04:20.485 | error | host.Medion(Home) Caught by controller[0]: requireStack: [
host.MedionHome) | 2021-09-19 11:04:20.485 | error | host.Medion(Home) Caught by controller[0]: code: 'MODULE_NOT_FOUND',
host.MedionHome) | 2021-09-19 11:04:20.485 | error | host.Medion(Home) Caught by controller[0]: at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
host.MedionHome) | 2021-09-19 11:04:20.485 | error | host.Medion(Home) Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:708:14)
host.MedionHome) | 2021-09-19 11:04:20.485 | error | host.Medion(Home) Caught by controller[0]: at Module.load (internal/modules/cjs/loader.js:863:32)
host.MedionHome) | 2021-09-19 11:04:20.485 | error | host.Medion(Home) Caught by controller[0]: at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
host.MedionHome) | 2021-09-19 11:04:20.484 | error | host.Medion(Home) Caught by controller[0]: at Module._compile (internal/modules/cjs/loader.js:999:30)
host.MedionHome) | 2021-09-19 11:04:20.484 | error | host.Medion(Home) Caught by controller[0]: at Object.<anonymous> (C:\Program Files\iobroker\Home\node_modules\iobroker.xterm\main.js:12:18)
host.MedionHome) | 2021-09-19 11:04:20.484 | error | host.Medion(Home) Caught by controller[0]: at require (internal/modules/cjs/helpers.js:74:18)
host.MedionHome) | 2021-09-19 11:04:20.484 | error | host.Medion(Home) Caught by controller[0]: at Module.require (internal/modules/cjs/loader.js:887:19)
host.MedionHome) | 2021-09-19 11:04:20.484 | error | host.Medion(Home) Caught by controller[0]: at Function.Module._load (internal/modules/cjs/loader.js:667:27)
host.MedionHome) | 2021-09-19 11:04:20.484 | error | host.Medion(Home) Caught by controller[0]: at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
host.MedionHome) | 2021-09-19 11:04:20.484 | error | host.Medion(Home) Caught by controller[0]: - C:\Program Files\iobroker\Home\node_modules\iobroker.xterm\main.js
host.MedionHome) | 2021-09-19 11:04:20.484 | error | host.Medion(Home) Caught by controller[0]: Require stack:
host.MedionHome) | 2021-09-19 11:04:20.483 | error | host.Medion(Home) Caught by controller[0]: Error: Cannot find module 'node-pty'
host.MedionHome) | 2021-09-19 11:04:20.483 | error | host.Medion(Home) Caught by controller[0]:
host.MedionHome) | 2021-09-19 11:04:20.483 | error | host.Medion(Home) Caught by controller[0]: ^
host.MedionHome) | 2021-09-19 11:04:20.483 | error | host.Medion(Home) Caught by controller[0]: throw err;
host.MedionHome) | 2021-09-19 11:04:20.483 | error | host.Medion(Home) Caught by controller[0]: internal/modules/cjs/loader.js:818
host.MedionHome) | 2021-09-19 11:03:49.725 | error | host.Medion(Home) instance system.adapter.xterm.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.MedionHome) | 2021-09-19 11:03:49.725 | error | host.Medion(Home) Caught by controller[0]: }
host.MedionHome) | 2021-09-19 11:03:49.725 | error | host.Medion(Home) Caught by controller[0]: ]
host.MedionHome) | 2021-09-19 11:03:49.725 | error | host.Medion(Home) Caught by controller[0]: 'C:\\Program Files\\iobroker\\Home\\node_modules\\iobroker.xterm\\main.js'

</body>
</html>`

Plattform: Windows
RAM: 16 GB 
Node.js: 12.22.6
NPM: 6.14.15
JS Controller: 3.3.18
Admin: 5.1.25
Web: 3.4.9
Socket.io: 3.1.4
Script Engine: 5.2.13
IOT: 1.8.23
VIS: 1.4.4

**Comment by Apollon77** [comment]
Please try to reinstall

**Comment by Apollon77** [comment]
Weill be "fixed" in next update ... but in fact check why node-pty was not installed correctly
