### ISSUE TITLE
Update stable version in repo from 1.1.0 to 2.0.1

### ISSUE THREAD

**Issue by GermanBluefox** [ioBroker/ioBroker.xterm#103]
# Think about update stable version to 2.0.1
**Version**: stable=**1.1.0** (360 days old) => latest=**2.0.1** (15 days old)
**Installs**: stable=**417** (81.13%), latest=**41** (7.98%), total=**514**

Click to use [developer portal](https://www.iobroker.dev/adapter/xterm/releases)
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json#L2956)

Note: This is an automatically generated message and not personally authored by bluefox!

**Comment by mcm1957** [comment]
@GermanBluefox
@Apollon77

Is there any reason to delay publishing at stable repository any longer?

**If there is no comment until end of November we might upgrade stable repository anyway!**

**Comment by mcm1957** [comment]
update confirmed by @GermanBluefox at 6.11.2023 by telegram

**Comment by GermanBluefox** [comment]
This issue seems to be outdated.

This issue suggests to update the stable version of this adapter to 2.0.1 but the current stable version is already 2.0.1.

So this issue should be closed.
