### ISSUE TITLE
not working in docker

### ISSUE THREAD

**Issue by Anzic23** [ioBroker/ioBroker.xterm#2]
**Describe the bug**  
adapter does not start
**To Reproduce**  
1. install adapter in docker
2. See error

**Expected behavior**  
it must work

**Screenshots & Logfiles**  
<html>
<body>

xterm.0 | 2021-11-08 00:47:19.894 | debug | XTerm is listening on 7099
-- | -- | -- | --
xterm.0 | 2021-11-08 00:47:19.892 | debug | Using http createServer
xterm.0 | 2021-11-08 00:47:19.853 | info | starting. Version 0.2.0 in /opt/iobroker/node_modules/iobroker.xterm, node: v12.22.5, js-controller: 3.3.18
xterm.0 | 2021-11-08 00:47:19.127 | debug | Plugin sentry Initialize Plugin (enabled=true)
host.iobroker | 2021-11-08 00:47:17.065 | info | instance system.adapter.xterm.0 started with pid 6667

</body>
</html>
**Versions:**  
 - Adapter version: 0.2.0
 - JS-Controller version: 3.3.18
 - Node version: <node-version> v12.22.5
 - Operating system: docker 5.1.0

**Additional context**  
and when the port changes, the cursor 'jumps' to the end. Also, there is no way to press the save and save and close button.

**Comment by Apollon77** [comment]
What exactly is not working? I can not see any error

**Comment by Anzic23** [comment]
Now I checked, it started with a yellow icon. When I try to connect, a login window pops up. But I don't understand what user is in the container? can't get into CLI

**Comment by Apollon77** [comment]
Here you need to enter iobroker credentials ... so from an ioBroker user

**Comment by Anzic23** [comment]
Thanks, managed go into the CLI.
By the way, I found a bug, if I erase the text with a backspace, then the cursor moves forward, not backward, while the text is actually deleted, but not on the screen, only the cursor moves forward.
![image](https://user-images.githubusercontent.com/37106885/158069073-9b207576-da08-4c14-94f3-a7920c02e008.png)

![image](https://user-images.githubusercontent.com/37106885/158069083-d8076dc9-108e-45e8-b5dd-56b4c3bd698b.png)

**Comment by Apollon77** [comment]
Please create own issue for this ... also no idea if it is from us or from the used xterm lib
