### ISSUE TITLE
"Let's encrypt" module import is deprecated

### ISSUE THREAD

**Issue by marlan99** [ioBroker/ioBroker.xterm#86]
Adapter Version: 1.1.0
NodeJS: 18.16.1
NPM: 9.5.1
JS-Controller: 5.0.5

when starting the instance i get the following warning:

`Information for Developer: Using the direct "Let's encrypt" module import is deprecated and will be removed in the next js-controller version, use @iobroker/webserver instead`

**Comment by GermanBluefox** [comment]
Done
